### ISSUE TITLE
Release 0.0.3 so that hapi plugin actually works

### ISSUE THREAD

**Issue by ggoodman** [Netflix/falcor-hapi#11]
Please consider `npm publish`ing to address #10 which results in hapi never completing startup.

**Comment by phated** [comment]
:+1: Ran into this problem and had to install from git

**Comment by mattwoolnough** [comment]
:+1: me too.

**Comment by jakobrosenberg** [comment]
No replies since September. Is anyone maintaining this project?

**Comment by michaelbpaulson** [comment]
Hello.  Very sorry.  I don't really know if anyone is _maintaining_ this project, but I can certainly produce an NPM release for this.  Let me check with the team to see if there are any formalities I need to go through then I'll pull the trigger.

**Comment by jakobrosenberg** [comment]
@michaelbpaulson Thank you. Very appreciated.

**Comment by michaelbpaulson** [comment]
boom.  https://www.npmjs.com/package/falcor-hapi
